[General]
CurrentConfig=1
Language=zh-CN

[Config1]
SavePath=D:\Documents
# One line for name, one line for description, terminated by '*'
WorldData=
Adobe

AweSun Files

Books

C++ Primer Plus附录文件和源代码

Dism++10.1.1002.1B

Music

OneNote Notebooks

Programs

Quicker

Software

Tencent Files

Visual Studio 2022

xwechat_files

Zoom

录音

演示用备份

演示用文件夹

自定义 Office 模板

视频

驱动

*
BackupPath=D:\Documents
ZipProgram=C:\Users\Admin\AppData\Local\Temp\7z84C2.tmp.exe
ZipFormat=7z
ZipLevel=5
KeepCount=10
SmartBackup=1
RestoreBeforeBackup=0
HotBackup=0
TopMost=0
ManualRestore=1
SilenceMode=0
Theme=1
Font=C:\Windows\Fonts\msyh.ttc
ThemeColor=
BackupNaming=0
SilenceMode=0


